---
- hosts: lb 
  remote_user: root

  vars:
    haproxy_backend_servers:
      - name: app1
        address: 127.0.0.1:8080
      - name: app2
        address: 127.0.0.2:8080
  roles:
    - ansible-role-haproxy
